### ISSUE TITLE
Bug during the CI

### ISSUE THREAD

**Issue by tercierp** [SwEnt-Group8/Street-work-app#44]
Sometimes, during the execution of the IC, tests don't work. In order to characterize the problem more precisely, I'm going to list them to get an overview of which tests don't work over several executions.

Non-exhaustive list of tests that don't work:
```bash
com.android.streetworkapp.ui.authentication.LoginTest > uiComponentsDisplayed[emulator-5554 - 14] FAILED 
	java.lang.NullPointerException: Current state was null unexpectedly. Last stage = STARTED
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)
E1017 21:02:45.482061    3205 FrameBuffer.cpp:3628] Failed to find ColorBuffer:803
E1017 21:02:52.529073    3205 FrameBuffer.cpp:3628] Failed to find ColorBuffer:892
Tests on emulator-5554 - 14 failed: There was 1 failure(s).
```
[CI execution link](https://github.com/SwEnt-Group8/Street-work-app/actions/runs/11392928203/job/31700104936)

**Comment by tercierp** [comment]
The problem came up again during a CI execution today, if we look a little more carefully [on the internet](https://github.com/facebook/react-native/issues/43320#issuecomment-1992595432), this problem may be due to the version according to this answer.

**Comment by Simmanz** [comment]
Found another error in the CI that is solved by re-running it : 

```> 
Task :app:dexBuilderDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
59 actionable tasks: 11 executed, 12 from cache, 36 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAndroidTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./

BUILD FAILED in 9s
Error: The process '/usr/bin/sh' failed with exit code 1
```

**Comment by Simmanz** [comment]
Another error that should not have happened (passed before, sole commit between modified files that are not related).

Link : [CI Execution](https://github.com/SwEnt-Group8/Street-work-app/actions/runs/12070957400/job/33661602892?pr=148)

````
> Task :app:connectedDebugAndroidTest
Starting 95 tests on emulator-5554 - 14

com.android.streetworkapp.end2end.End2EndCreateEvent > e2eCanCreateEventAndDisplayIt[emulator-5554 - 14] SKIPPED 

com.android.streetworkapp.end2end.End2EndParks > E2ECanClickParkAncAccessSpecificParkOverview[emulator-5554 - 14] SKIPPED 

com.android.streetworkapp.ui.authentication.LoginTest > uiComponentsDisplayed[emulator-5554 - 14] FAILED 
	java.lang.IllegalStateException: No compose hierarchies found in the app. Possible reasons include: (1) the Activity that calls setContent did not launch; (2) setContent was not called; (3) setContent was called before the ComposeTestRule ran. If setContent is called by the Activity, make sure the Activity is launched after the ComposeTestRule runs
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:87)
E1128 14:44:58.804697    3648 FrameBuffer.cpp:3628] Failed to find ColorBuffer:699
E1128 14:44:59.745709    3648 FrameBuffer.cpp:3628] Failed to find ColorBuffer:703
E1128 14:46:22.984024    3648 FrameBuffer.cpp:3628] Failed to find ColorBuffer:3013
Tests on emulator-5554 - 14 failed: There was 1 failure(s).
``

**Comment by Simmanz** [comment]
Almost the same as the previous one (uiComponentsDisplayedOnThirdPage). My PR did not touch SignIn or its components.

Happened while working in Profile for Friend removal : [PR link](https://github.com/SwEnt-Group8/Street-work-app/pull/185)

Link : [CI Execution](https://github.com/SwEnt-Group8/Street-work-app/actions/runs/12142062707/job/33855621178?pr=185)

```
> Task :app:connectedDebugAndroidTest
Starting 110 tests on emulator-5554 - 14

com.android.streetworkapp.end2end.End2EndCreateEvent > e2eCanCreateEventAndDisplayIt[emulator-5554 - 14] SKIPPED 

com.android.streetworkapp.end2end.End2EndParks > E2ECanClickParkAncAccessSpecificParkOverview[emulator-5554 - 14] SKIPPED 
E1203 14:52:08.432288    3521 FrameBuffer.cpp:3628] Failed to find ColorBuffer:551
E1203 14:52:12.818754    3521 FrameBuffer.cpp:3628] Failed to find ColorBuffer:614

com.android.streetworkapp.ui.authentication.LoginTest > uiComponentsDisplayedOnThirdPage[emulator-5554 - 14] FAILED 
	java.lang.IllegalStateException: No compose hierarchies found in the app. Possible reasons include: (1) the Activity that calls setContent did not launch; (2) setContent was not called; (3) setContent was called before the ComposeTestRule ran. If setContent is called by the Activity, make sure the Activity is launched after the ComposeTestRule runs
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:87)
E1203 14:52:20.723791    3521 FrameBuffer.cpp:3628] Failed to find ColorBuffer:731
E1203 14:52:24.453018    3521 FrameBuffer.cpp:3628] Failed to find ColorBuffer:790
E1203 14:52:33.912906    3521 FrameBuffer.cpp:3628] Failed to find ColorBuffer:897
Tests on emulator-5554 - 14 failed: There was 1 failure(s).

> Task :app:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/runner/work/Street-work-app/Street-work-app/app/build/reports/androidTests/connected/debug/index.html
```
